export interface RefrigerantDetail {
  slug: string;
  name: string;
  formula: string;
  safetyClass: string;
  gwp: number;
  odp: number;
  compatibleOil: string;
  applications: string[];
  charging: string[];
  leakDetection: string[];
  recovery: string[];
  retrofit: string;
  // Antoine parameters to compute saturation pressure: P (bar) = 10^(A - B / (T + C))
  // T in Celsius
  antoine: { A: number; B: number; C: number };
}

export const refrigerantsData: Record<string, RefrigerantDetail> = {
  r22: {
    slug: "r22",
    name: "R-22 (HCFC-22)",
    formula: "CHFCIF2",
    safetyClass: "A1 (Non-Toxic, Non-Flammable)",
    gwp: 1810,
    odp: 0.055,
    compatibleOil: "Mineral Oil (MO) or Alkylbenzene (AB)",
    applications: [
      "Older residential split ACs",
      "Packaged commercial units",
      "Medium temperature refrigeration loops",
    ],
    charging: [
      "Can be charged in either liquid or vapor phase since it is a single-component pure gas.",
      "Charge slowly into the suction side if charging as vapor, checking gas pressures and current draw.",
    ],
    leakDetection: [
      "Soap bubble solution test",
      "Electronic halogen leak detectors",
      "UV fluorescent dye checks",
    ],
    recovery: [
      "Must recover using dedicated R-22 recovery cylinders. Venting is illegal in India (under Ozone Rules).",
    ],
    retrofit:
      "Retrofitted with R-407C or R-427A, requiring mineral oil flushing and POE lubricant swap.",
    antoine: { A: 4.148, B: 871.4, C: 247.9 }, // Antoine coefficients
  },
  r32: {
    slug: "r32",
    name: "R-32 (HFC-32)",
    formula: "CH2F2",
    safetyClass: "A2L (Mildly Flammable)",
    gwp: 675,
    odp: 0,
    compatibleOil: "Synthetic Polyolester (POE) Oil",
    applications: ["Modern high-efficiency split ACs", "Inverter multi-splits"],
    charging: [
      "Single-component gas: can be charged as liquid or vapor.",
      "Liquid charging is highly recommended to expedite process and maintain accuracy.",
      "Use spark-proof, brushless recovery and charging scales due to flammability.",
    ],
    leakDetection: ["A2L compatible heated diode electronic leak detectors", "Soap bubble test"],
    recovery: [
      "Recover using flame-proof recovery machines into R-32 rated containers with left-hand threads.",
    ],
    retrofit:
      "Cannot retrofit into older R-22 or R-410A systems due to high operating discharge temperatures and A2L flammability ratings.",
    antoine: { A: 4.256, B: 900.5, C: 251.2 },
  },
  r410a: {
    slug: "r410a",
    name: "R-410A",
    formula: "R-32 / R-125 (50% / 50%)",
    safetyClass: "A1 (Non-Toxic, Non-Flammable)",
    gwp: 2088,
    odp: 0,
    compatibleOil: "Polyolester (POE) Oil",
    applications: ["Residential splits", "Commercial VRF/VRV systems", "Water chillers"],
    charging: [
      "Near-azeotropic blend: MUST charge as LIQUID from the cylinder liquid valve to prevent fractionation.",
      "Vapor charging will throw off the 50/50 blend ratio and reduce system capacity.",
    ],
    leakDetection: ["Electronic heated diode or infrared detectors", "Soap bubbles", "UV dye"],
    recovery: ["Recover into high pressure (400 PSI rating) recovery cylinders."],
    retrofit: "Not suitable for R-22 retrofit due to 60% higher operating pressures.",
    antoine: { A: 4.288, B: 934.3, C: 253.5 },
  },
  r404a: {
    slug: "r404a",
    name: "R-404A",
    formula: "R-125 / R-143a / R-134a (44% / 52% / 4%)",
    safetyClass: "A1 (Non-Toxic, Non-Flammable)",
    gwp: 3922,
    odp: 0,
    compatibleOil: "Polyolester (POE) Oil",
    applications: ["Commercial cold rooms", "Walk-in freezers", "Ice machines", "Blast freezers"],
    charging: [
      "MUST charge as LIQUID. Near-azeotropic blend.",
      "Flip the cylinder upside down (if no dip tube) and weigh in the exact charge.",
    ],
    leakDetection: ["Soap bubble solution", "Electronic leak detector (HFC-specific)"],
    recovery: ["Recover fully. Due to GWP of 3922, strict containment is required."],
    retrofit: "Can be retrofitted with R-448A (Opteon XP40) or R-449A to reduce GWP by 65%.",
    antoine: { A: 4.27, B: 910.1, C: 249.1 },
  },
  r407c: {
    slug: "r407c",
    name: "R-407C",
    formula: "R-32 / R-125 / R-134a (23% / 25% / 52%)",
    safetyClass: "A1 (Non-Toxic, Non-Flammable)",
    gwp: 1774,
    odp: 0,
    compatibleOil: "Polyolester (POE) Oil",
    applications: ["R22 retrofit systems", "Ducted ACs", "Air cooled chillers"],
    charging: [
      "Zeotropic blend: high temperature glide (approx 7°C). MUST charge as LIQUID.",
      "Vapor charging will fractionate the refrigerant blend.",
    ],
    leakDetection: ["Infrared electronic leak detector", "Bubble check"],
    recovery: ["Standard recovery parameters apply."],
    retrofit: "Common drop-in retrofit for R-22, requires oil swap from mineral to POE.",
    antoine: { A: 4.31, B: 955.2, C: 254.8 },
  },
  r134a: {
    slug: "r134a",
    name: "R-134a (HFC-134a)",
    formula: "CH2FCF3",
    safetyClass: "A1 (Non-Toxic, Non-Flammable)",
    gwp: 1430,
    odp: 0,
    compatibleOil: "Polyolester (POE) Oil for stationary, PAG for automotive",
    applications: [
      "Domestic refrigerators",
      "Bottle coolers",
      "Display counters",
      "Centrifugal chillers",
    ],
    charging: [
      "Pure gas: can be charged as liquid or vapor.",
      "Charge vapor slowly through suction service valve or liquid through liquid line under vacuum.",
    ],
    leakDetection: ["Soap bubble solution", "Electronic halogen sensor"],
    recovery: ["Recover into dedicated R-134a cylinders."],
    retrofit: "Can replace R-12 in old systems after oil replacement and drier change.",
    antoine: { A: 4.412, B: 1042.8, C: 263.2 },
  },
  r290: {
    slug: "r290",
    name: "R-290 (Propane)",
    formula: "C3H8",
    safetyClass: "A3 (Highly Flammable)",
    gwp: 3,
    odp: 0,
    compatibleOil: "Mineral Oil (MO) or POE Oil",
    applications: ["Commercial deep freezers", "Display counters", "Small spot coolers"],
    charging: [
      "Highly flammable hydrocarbon. Max charge weight limit is strictly capped (typically 150g in India).",
      "Charge in liquid or vapor phase in a well-ventilated space with no ignition sources.",
    ],
    leakDetection: ["HC-compatible combustible gas sniffer", "Soap bubble solution"],
    recovery: [
      "Recover using specialized HC-safe machines or vent carefully in open outdoor air where permitted by local code.",
    ],
    retrofit:
      "Do not retrofit R-290 into systems not designed for hydrocarbons due to explosion risks.",
    antoine: { A: 3.928, B: 804.0, C: 247.0 },
  },
  r600a: {
    slug: "r600a",
    name: "R-600a (Isobutane)",
    formula: "i-C4H10",
    safetyClass: "A3 (Highly Flammable)",
    gwp: 3,
    odp: 0,
    compatibleOil: "Mineral Oil (MO)",
    applications: ["Domestic refrigerators", "Chest freezers"],
    charging: [
      "Charge limit: strictly under 150 grams per loop.",
      "Charge by weight using precise electronic scales.",
    ],
    leakDetection: ["Hydrocarbon sniffer", "Bubble test"],
    recovery: [
      "Venting is permitted in small quantities in open air, or recover using HC-safe equipment.",
    ],
    retrofit: "Do not retrofit in HFC refrigerators.",
    antoine: { A: 3.938, B: 871.2, C: 236.4 },
  },
  r717: {
    slug: "r717",
    name: "R-717 (Ammonia)",
    formula: "NH3",
    safetyClass: "B2L (Toxic, Mildly Flammable)",
    gwp: 0,
    odp: 0,
    compatibleOil: "Mineral Oil or Synthetic Alkylbenzene",
    applications: ["Large ice factories", "Cold storage warehouses", "Dairy processing plants"],
    charging: [
      "Highly toxic gas. Requires full breathing apparatus and face masks during charging.",
      "Charge into suction line as vapor or under vacuum.",
    ],
    leakDetection: [
      "Sulfur sticks (produces thick white smoke in presence of ammonia)",
      "Red litmus paper (turns blue)",
    ],
    recovery: ["Requires specialized industrial absorption recovery systems or scrubbers."],
    retrofit: "Ammonia corrodes copper. Can only be used in steel/aluminum systems.",
    antoine: { A: 4.869, B: 1113.9, C: 247.9 },
  },
  r744: {
    slug: "r744",
    name: "R-744 (Carbon Dioxide)",
    formula: "CO2",
    safetyClass: "A1 (Non-toxic, high pressure hazard)",
    gwp: 1,
    odp: 0,
    compatibleOil: "Polyolester (POE) or PAG Oil",
    applications: ["Transcritical supermarket refrigeration", "Pharma cold rooms"],
    charging: [
      "Extremely high pressures (up to 120 bar). Requires heavy-duty stainless steel fittings.",
      "Charge vapor first to raise pressure above triple point (5.2 bar) before charging liquid, to prevent dry ice formation.",
    ],
    leakDetection: ["CO2 electronic leak detector", "Bubble leak check"],
    recovery: [
      "Can be safely vented to atmosphere as it is carbon dioxide, though recovery is done in closed-loop systems.",
    ],
    retrofit: "Requires system replacement due to massive operating pressure variance.",
    antoine: { A: 4.6, B: 800.0, C: 250.0 },
  },
  r507: {
    slug: "r507",
    name: "R-507",
    formula: "R-125 / R-143a (50% / 50%)",
    safetyClass: "A1 (Non-Toxic, Non-Flammable)",
    gwp: 3985,
    odp: 0,
    compatibleOil: "Polyolester (POE) Oil",
    applications: ["Low temperature commercial freezers", "Supermarkets"],
    charging: ["Azeotropic blend. MUST charge as LIQUID to maintain correct proportions."],
    leakDetection: ["HFC sniffer", "Bubble test"],
    recovery: ["Strict containment due to high GWP of 3985."],
    retrofit: "Can replace R-502 or R-404A.",
    antoine: { A: 4.298, B: 915.2, C: 250.2 },
  },
  r448a: {
    slug: "r448a",
    name: "R-448A (Opteon XP40)",
    formula: "R-32/125/134a/1234yf/1234ze (26/26/21/20/7%)",
    safetyClass: "A1 (Non-Toxic, Non-Flammable)",
    gwp: 1273,
    odp: 0,
    compatibleOil: "POE Oil",
    applications: ["Commercial cold storage retrofits", "Supermarket display chillers"],
    charging: [
      "Zeotropic blend: MUST charge as LIQUID. Flip cylinder and charge through manifold scale.",
    ],
    leakDetection: ["Electronic sniffer", "Bubble checks"],
    recovery: ["Recover fully using HFO-rated recovery machines."],
    retrofit: "Excellent retrofit replacement for R-404A systems.",
    antoine: { A: 4.35, B: 980.0, C: 252.0 },
  },
  r449a: {
    slug: "r449a",
    name: "R-449A (Opteon XP40)",
    formula: "R-32/125/134a/1234yf (24.3/24.7/25.7/25.3%)",
    safetyClass: "A1 (Non-Toxic, Non-Flammable)",
    gwp: 1282,
    odp: 0,
    compatibleOil: "POE Oil",
    applications: ["Commercial refrigeration", "Chillers", "Walk-in cold rooms"],
    charging: ["MUST charge as LIQUID to avoid blend fractionation."],
    leakDetection: ["Electronic leak sniffer", "Bubble spray"],
    recovery: ["Recover into HFO-rated cylinders."],
    retrofit: "Drop-in replacement for R-404A systems.",
    antoine: { A: 4.348, B: 978.5, C: 251.8 },
  },
  r1234yf: {
    slug: "r1234yf",
    name: "R-1234yf (HFO-1234yf)",
    formula: "CH2=CFCF3",
    safetyClass: "A2L (Mildly Flammable)",
    gwp: 1,
    odp: 0,
    compatibleOil: "Polyalkylene Glycol (PAG) or POE Oil",
    applications: ["Automotive air conditioners", "Small commercial refrigerators"],
    charging: ["Charge as liquid or vapor. Liquid phase is preferred for stability."],
    leakDetection: ["A2L compatible sniffer", "Bubble solution"],
    recovery: ["Use spark-free HFO recovery units."],
    retrofit: "Replaces R-134a in automobile AC loops.",
    antoine: { A: 4.41, B: 1020.5, C: 260.0 },
  },
  r1234ze: {
    slug: "r1234ze",
    name: "R-1234ze (HFO-1234ze)",
    formula: "CF3CH=CHF",
    safetyClass: "A2L (Mildly Flammable)",
    gwp: 7,
    odp: 0,
    compatibleOil: "POE Oil",
    applications: ["Centrifugal liquid chillers", "Heat pumps", "Vending machines"],
    charging: ["HFO pure fluid: charge as liquid or vapor."],
    leakDetection: ["HFO/A2L sniffer", "Bubble spray"],
    recovery: ["Standard recovery procedures for low GWP HFOs apply."],
    retrofit: "Alternative for R-134a in commercial applications.",
    antoine: { A: 4.432, B: 1060.1, C: 262.1 },
  },
};
